INSERT INTO books (id, title, genre, author_id) VALUES
(1, 'It', 'Horror', 1),
(2, 'The Shining', 'Horror', 1),
(3, 'Harry Potter and the Sorcerer''s Stone', 'Fantasy', 2),
(4, 'Harry Potter and the Chamber of Secrets', 'Fantasy', 2),
(5, 'Pride and Prejudice', 'Romance', 3),
(6, 'Sense and Sensibility', 'Romance', 3),
(7, 'Nineteen Eighty-Four', 'Dystopian', 4),
(8, 'Animal Farm', 'Dystopian', 4),
(9, 'Murder on the Orient Express', 'Mystery', 5),
(10, 'And Then There Were None', 'Mystery', 5),
(11, 'The Sun Also Rises', 'Fiction', 6),
(12,'A Farewell to Arms', 'Fiction', 6),
(13, 'Hamlet', 'Drama', 7),
(14, 'Romeo and Juliet', 'Drama', 7),
(15, 'A Tale of Two Cities', 'Historical Fiction', 8),
(16, 'Great Expectations', 'Fiction', 8),
(17, 'War and Peace', 'Historical Fiction', 9),
(18, 'Anna Karenina', 'Fiction', 9),
(19, 'Crime and Punishment', 'Fiction', 10),
(20, 'The Brothers Karamazov', 'Fiction', 10);